<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Добавить',
    'Article categories list' => 'Список категорий',
    'Articles' => 'Статьи',
    'Articles list' => 'Список статей',
    'Articles view name' => '',
    'Basic' => 'Основные настройки',
    'Categories list' => 'Список категорий',
    'Category' => 'Категория',
    'Color' => 'Цвет',
    'Created' => '@@Создано@@',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit' => 'Редактировать',
    'Edit article' => 'Редактировать статью',
    'For social networks' => 'Для соцсетей',
    'Full description' => 'Полное описание',
    'Image' => '@@Изображение@@',
    'Image URL' => 'URL картинки',
    'Image preview' => 'Миниатюра',
    'Images' => 'Изображения',
    'Key' => '',
    'Language' => 'Язык',
    'Menu item' => 'Пункт меню',
    'Name' => 'Наименование',
    'Not selected' => 'Не выбрана',
    'Parent category' => 'Родительская категория',
    'Position' => 'Позиция',
    'Publish date' => 'Дата публикации',
    'Save' => 'Сохранить',
    'Save article' => '@@Сохранить@@',
    'Seo Data' => 'SEO данные',
    'Seo Description' => 'SEO описание',
    'Seo Keywords' => 'SEO Ключевые слова',
    'Seo Title' => 'SEO заглавие',
    'Seo Url' => 'SEO URL (адрес)',
    'Short description' => 'Краткое описание',
    'Show' => 'Показывать',
    'Show articles' => 'Показывать статьи',
    'Tech' => '',
    'Thumbnail' => 'Миниатюра',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Upload' => 'Загрузить с компьютера',
    'Upload image' => 'Загрузить изображение',
    'View Name' => '',
    'View name' => '',
    'Without category' => '@@Без категории@@',
];
