<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Додати',
    'Article categories list' => 'Список категорій',
    'Articles' => 'Статті',
    'Articles list' => 'Список статей',
    'Articles view name' => '',
    'Basic' => 'Основні налаштування',
    'Categories list' => 'Список категорій',
    'Category' => 'Категорія',
    'Color' => 'Колір',
    'Created' => '@@Створено@@',
    'Delete' => 'Видалити',
    'Description' => 'Опис',
    'Edit' => 'Редагувати',
    'Edit article' => 'Редагувати статтю',
    'For social networks' => 'Для соцмереж',
    'Full description' => 'Повний опис',
    'Image' => '@@Зображення@@',
    'Image URL' => 'URL картинки',
    'Image preview' => 'Мініатюра',
    'Images' => 'Зображення',
    'Key' => '',
    'Language' => 'Мова',
    'Menu item' => 'Пункт меню',
    'Name' => 'Найменування',
    'Not selected' => 'Не обрана ',
    'Parent category' => 'Родинна категорія',
    'Position' => 'Позиція',
    'Publish date' => 'Дата публікації',
    'Save' => 'Зберегти',
    'Save article' => '@@Зберегти@@',
    'Seo Data' => 'SEO дані',
    'Seo Description' => 'SEO опис',
    'Seo Keywords' => 'SEO Ключові слова',
    'Seo Title' => 'SEO назву',
    'Seo Url' => 'SEO URL (адресу)',
    'Short description' => 'Короткий опис',
    'Show' => 'Показувати',
    'Show articles' => 'Показувати статті',
    'Tech' => '',
    'Thumbnail' => 'Мініатюра',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Upload' => 'Завантажити з комп\'ютера',
    'Upload image' => 'Завантажити зображення',
    'View Name' => '',
    'View name' => '',
    'Without category' => '@@Без категорії@@',
];
